// <auto-generated />
using System;
using JamesAmos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JamesAmos.Migrations
{
    [DbContext(typeof(JamesAmosDbContext))]
    [Migration("20190614165238_change")]
    partial class change
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JamesAmos.Models.DailyPrayer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Book");

                    b.Property<string>("Chapter");

                    b.Property<string>("Number");

                    b.Property<string>("Verse");

                    b.HasKey("ID");

                    b.ToTable("DailyPrayer");
                });

            modelBuilder.Entity("JamesAmos.Models.HomePage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardOneImageUrl");

                    b.Property<string>("CardOneText");

                    b.Property<string>("CardOneTitle");

                    b.Property<string>("CardThreeImageUrl");

                    b.Property<string>("CardThreeText");

                    b.Property<string>("CardThreeTitle");

                    b.Property<string>("CardTwoImageUrl");

                    b.Property<string>("CommitText1");

                    b.Property<string>("CommitText2");

                    b.Property<string>("CommitText3");

                    b.Property<string>("CommitTitle1");

                    b.Property<string>("CommitTitle2");

                    b.Property<string>("CommitTitle3");

                    b.Property<string>("CommitmentHeader");

                    b.Property<int?>("DailyVerseID");

                    b.Property<string>("HeaderImageUrl");

                    b.Property<string>("HeaderSubTitle");

                    b.Property<string>("HeaderTitle");

                    b.Property<string>("WhyText1");

                    b.Property<string>("WhyTitle1");

                    b.HasKey("ID");

                    b.HasIndex("DailyVerseID");

                    b.ToTable("HomePage");
                });

            modelBuilder.Entity("JamesAmos.Models.Vlog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Subject");

                    b.Property<string>("VideoUrl");

                    b.HasKey("ID");

                    b.ToTable("Vlogs");
                });

            modelBuilder.Entity("JamesAmos.Models.HomePage", b =>
                {
                    b.HasOne("JamesAmos.Models.DailyPrayer", "DailyVerse")
                        .WithMany()
                        .HasForeignKey("DailyVerseID");
                });
#pragma warning restore 612, 618
        }
    }
}
